import test from 'node:test';import assert from 'node:assert/strict';import {roundFixture} from './scripts/chapter-two-followup-fixture.mjs';import {startSecondChapterAccess,advance,options,blockedReason,decodeSave,newGame} from './engine.mjs';import {accessSummary,accessReaction} from './chapter-two-access.mjs';import {publishedSupplement} from './chapter-two-public.mjs';import {commitments} from './chapter-meta.mjs';import {exportSave,importSave} from './save-transfer.mjs';import {recordPlayTime} from './playtime.mjs';import {ambienceFor} from './ambience.mjs';
test('192 access and source reply routes preserve privacy, original evidence and obligations',()=>{
 let count=0;for(const mode of ['verified','held','missing'])for(const published of [true,false])for(const file of ['public','reasons'])for(const inquiry of ['records','pause']){const old=roundFixture({mode,published,file,inquiry}),snapshot=JSON.stringify(old);
 for(const action of options(startSecondChapterAccess(old)))for(const check of ['check','hold'])for(const focus of ['timeline','access']){
 let s=advance(startSecondChapterAccess(old),action.id);assert.deepEqual(decodeSave(JSON.stringify(s)),s);assert.match(accessReaction(s),inquiry==='pause'?/來源主動補充/:/延續先前的日期追問/);s=advance(s,check);assert.deepEqual(decodeSave(JSON.stringify(s)),s);s=advance(s,focus);assert.deepEqual(importSave(JSON.stringify(exportSave(s))),s);assert.deepEqual(s.evidence,{...old.evidence,E09:{verified:false,authorized:false}});assert.match(blockedReason(s,{requires:['E09']}),/尚未核實/);assert.deepEqual(s.tasks,old.tasks);assert.deepEqual(s.stats,old.stats);assert.deepEqual(commitments(s),commitments(old));assert.deepEqual(publishedSupplement(s),publishedSupplement(old));assert.equal(s.flags.c02SentQuestions,old.flags.c02SentQuestions);assert.equal(s.flags.c02RoundStaff,old.flags.c02RoundStaff);assert.equal(s.scene,'c02AccessEnd');assert.equal(recordPlayTime(s,1000,true),s);assert.equal(ambienceFor(s.scene),null);assert.throws(()=>startSecondChapterAccess(s));assert.match(accessSummary(s)[1].status,check==='check'?/來源仍未核實/:/尚未查核/);count++;
 }assert.equal(JSON.stringify(old),snapshot);}assert.equal(count,192);
});
test('old round saves continue; premature private replies, scope mismatches and forged source authority fail',()=>{
 const old=roundFixture(),s=startSecondChapterAccess(old);assert.deepEqual(decodeSave(JSON.stringify(old)),old);assert.throws(()=>startSecondChapterAccess(newGame()));
 for(const bad of [{...old,evidence:{...old.evidence,E09:{verified:false,authorized:false}}},{...s,scene:'c02AccessEnd'},{...s,flags:{...s.flags,c02AccessNext:'timeline'}},{...s,scene:'c02SourceReply',flags:{...s.flags,c02AccessAction:'appeal'},evidence:{...s.evidence,E09:{verified:false,authorized:false}}}])assert.equal(decodeSave(JSON.stringify(bad)),null);
 const reply=advance(s,'onsite');for(const e of [{verified:true,authorized:false},{verified:false,authorized:true}])assert.equal(decodeSave(JSON.stringify({...reply,evidence:{...reply.evidence,E09:e}})),null);
});
