import test from 'node:test';import assert from 'node:assert/strict';import {executionFixture} from './scripts/chapter-two-followup-fixture.mjs';import {startSecondChapterRound,advance,options,decodeSave,newGame} from './engine.mjs';import {canOnboard,roundSummary} from './chapter-two-round.mjs';import {publishedSupplement} from './chapter-two-public.mjs';import {commitments} from './chapter-meta.mjs';import {exportSave,importSave} from './save-transfer.mjs';import {recordPlayTime} from './playtime.mjs';import {ambienceFor} from './ambience.mjs';
const routes=[{staff:'independent',action:'sort'},{staff:'joint',action:'confirm'},{staff:'joint',action:'wait'},{accepted:false,staff:'joint',action:'own'},{accepted:false,staff:'joint',action:'resend'}];
test('120 second-round routes enforce ordering, original records and actual onboarding prerequisites',()=>{
 let count=0;for(const mode of ['verified','held','missing'])for(const next of ['files','staff'])for(const route of routes){const old=executionFixture({...route,mode,next}),snapshot=JSON.stringify(old);
 for(const file of ['public','reasons'])for(let staffChoice=0;staffChoice<2;staffChoice++){
 let s=startSecondChapterRound(old);assert.deepEqual(decodeSave(JSON.stringify(s)),s);for(const branch of next==='files'?['files','staff']:['staff','files']){assert.equal(options(s).length,1);assert.equal(options(s)[0].id,branch);s=advance(s,branch);assert.deepEqual(decodeSave(JSON.stringify(s)),s);if(branch==='staff')assert.equal(options(s).some(o=>o.id==='active'),canOnboard(old));s=advance(s,branch==='files'?file:options(s)[staffChoice].id);assert.deepEqual(decodeSave(JSON.stringify(s)),s);}
 assert.equal(s.scene,'c02RoundReport');s=advance(s,'record');assert.deepEqual(importSave(JSON.stringify(exportSave(s))),s);assert.deepEqual(s.evidence,{...old.evidence,E08:{verified:true,authorized:true}});assert.deepEqual(s.tasks,old.tasks);assert.deepEqual(s.stats,old.stats);assert.deepEqual(commitments(s),commitments(old));assert.deepEqual(publishedSupplement(s),publishedSupplement(old));assert.equal(s.flags.c02SentQuestions,old.flags.c02SentQuestions);assert.equal(s.flags.c02ProposalOutcome,old.flags.c02ProposalOutcome);assert.equal(s.scene,'c02RoundEnd');assert.equal(recordPlayTime(s,1000,true),s);assert.equal(ambienceFor(s.scene),null);assert.throws(()=>startSecondChapterRound(s));if(s.flags.c02RoundStaff==='active')assert.match(roundSummary(s)[1].status,/輪值已到任/);count++;
 }assert.equal(JSON.stringify(old),snapshot);}assert.equal(count,120);
});
test('old saves work; forged E08, out-of-order progress and unsupported arrival fail',()=>{
 const old=executionFixture(),entered=startSecondChapterRound(old);assert.deepEqual(decodeSave(JSON.stringify(old)),old);assert.throws(()=>startSecondChapterRound(newGame()));
 for(const bad of [{...old,evidence:{...old.evidence,E08:{verified:true,authorized:true}}},{...entered,scene:'c02RoundEnd'},{...entered,scene:'c02RoundStaff'},{...entered,flags:{...entered.flags,c02RoundStaff:'active'}},{...entered,flags:{...entered.flags,c02RoundRecorded:true}}])assert.equal(decodeSave(JSON.stringify(bad)),null);
 const files=advance(advance(entered,'files'),'public');assert.equal(decodeSave(JSON.stringify({...files,evidence:old.evidence})),null);assert.equal(decodeSave(JSON.stringify({...files,evidence:{...files.evidence,E08:{verified:false,authorized:true}}})),null);
});
