import test from 'node:test';import assert from 'node:assert/strict';import {proposalFixture} from './scripts/chapter-two-followup-fixture.mjs';import {startSecondChapterExecution,advance,options,decodeSave,newGame} from './engine.mjs';import {canSendQuestions,executionSummary,questionListText} from './chapter-two-execution.mjs';import {publishedSupplement} from './chapter-two-public.mjs';import {commitments} from './chapter-meta.mjs';import {exportSave,importSave} from './save-transfer.mjs';import {recordPlayTime} from './playtime.mjs';import {ambienceFor} from './ambience.mjs';
test('204 execution routes distinguish unsigned work, joint slots and publication authority, preserving prior duties',()=>{
 let count=0;for(const mode of ['verified','held','missing'])for(const published of [true,false])for(const boundary of ['questions','closed'])for(const staff of ['independent','joint'])for(const accepted of [true,false]){
 const old=proposalFixture({mode,published,boundary,staff,accepted}),snapshot=JSON.stringify(old);for(const action of options(startSecondChapterExecution(old))){
 let s=advance(startSecondChapterExecution(old),action.id);assert.deepEqual(decodeSave(JSON.stringify(s)),s);assert.match(executionSummary(s)[0].status,/回報待收/);assert.equal(options(s).some(c=>c.id==='send'),canSendQuestions(old));
 for(const list of options(s))for(const next of ['files','staff']){let result=advance(s,list.id);assert.deepEqual(decodeSave(JSON.stringify(result)),result);result=advance(result,next);assert.deepEqual(importSave(JSON.stringify(exportSave(result))),result);assert.equal(result.scene,'c02ExecutionEnd');assert.deepEqual(result.evidence,old.evidence);assert.deepEqual(result.tasks,old.tasks);assert.deepEqual(result.stats,old.stats);assert.deepEqual(commitments(result),commitments(old));assert.deepEqual(publishedSupplement(result),publishedSupplement(old));assert.equal(result.flags.c02ProposalOutcome,old.flags.c02ProposalOutcome);assert.equal(result.flags.c02SentQuestions,list.id==='send'?questionListText(old):undefined);assert.equal(recordPlayTime(result,1000,true),result);assert.equal(ambienceFor(result.scene),null);assert.throws(()=>startSecondChapterExecution(result));count++;}
 }assert.equal(JSON.stringify(old),snapshot);}assert.equal(count,204);
});
test('old proposal saves continue; forged action, premature report and unauthorized question publication are rejected',()=>{
 const old=proposalFixture({accepted:false}),s=startSecondChapterExecution(old);assert.deepEqual(decodeSave(JSON.stringify(old)),old);assert.throws(()=>startSecondChapterExecution(newGame()));
 for(const bad of [{...old,flags:{...old.flags,c02SentQuestions:'hidden'}},{...s,scene:'c02ExecutionEnd'},{...s,scene:'c02WorkList',flags:{...s.flags,c02WorkAction:'confirm'}},{...s,scene:'c02FirstReport',flags:{...s.flags,c02WorkAction:'own',c02ListDisposition:'sent',c02SentQuestions:questionListText(s)}}])assert.equal(decodeSave(JSON.stringify(bad)),null);
 let valid=advance(advance(startSecondChapterExecution(proposalFixture()),'sort'),'send');assert.equal(decodeSave(JSON.stringify({...valid,flags:{...valid.flags,c02SentQuestions:'changed'}})),null);
});
