import test from 'node:test';import assert from 'node:assert/strict';import {readingFixture} from './scripts/chapter-two-followup-fixture.mjs';import {startSecondChapterInquiry,advance,options,decodeSave,newGame} from './engine.mjs';import {questionOutline,inquirySummary} from './chapter-two-inquiry.mjs';import {publishedSupplement} from './chapter-two-public.mjs';import {commitments} from './chapter-meta.mjs';import {exportSave,importSave} from './save-transfer.mjs';import {recordPlayTime} from './playtime.mjs';import {ambienceFor} from './ambience.mjs';
test('144 inquiry routes enforce reading and date scope, preserve evidence and internal drafts across transfers',()=>{
 let count=0;for(const mode of ['verified','held','missing'])for(const published of [true,false])for(const readingChoice of ['read','postpone'])for(const dateChoice of ['compare','hold']){const old=readingFixture({mode,published,readingChoice,dateChoice}),snapshot=JSON.stringify(old);
 for(const topic of options(startSecondChapterInquiry(old))){let draft=advance(startSecondChapterInquiry(old),topic.id);assert.deepEqual(decodeSave(JSON.stringify(draft)),draft);assert.equal(options(draft).some(c=>c.id==='dates'),dateChoice==='compare');
 for(const focus of options(draft)){let review=advance(draft,focus.id);assert.deepEqual(decodeSave(JSON.stringify(review)),review);assert.equal(review.flags.c02QuestionText,questionOutline(review));assert.match(inquirySummary(review)[1].status,/待審閱/);
 for(const disposition of ['review','hold']){const s=advance(review,disposition);assert.deepEqual(importSave(JSON.stringify(exportSave(s))),s);assert.equal(s.scene,'c02InquiryEnd');assert.deepEqual(s.evidence,old.evidence);assert.deepEqual(s.tasks,old.tasks);assert.deepEqual(s.stats,old.stats);assert.deepEqual(commitments(s),commitments(old));assert.deepEqual(publishedSupplement(s),publishedSupplement(old));assert.equal(s.flags.c02SentQuestions,old.flags.c02SentQuestions);assert.equal(s.flags.c02QuestionText,review.flags.c02QuestionText);assert.match(inquirySummary(s)[1].status,disposition==='review'?/回覆待收/:/核對未安排/);assert.equal(recordPlayTime(s,1000,true),s);assert.equal(ambienceFor(s.scene),null);assert.throws(()=>startSecondChapterInquiry(s));count++;}
 }}assert.equal(JSON.stringify(old),snapshot);}assert.equal(count,144);
});
test('old reading saves continue; premature drafts, unsupported dates and fabricated reading topics fail',()=>{
 const old=readingFixture({readingChoice:'postpone',dateChoice:'hold'}),s=startSecondChapterInquiry(old);assert.deepEqual(decodeSave(JSON.stringify(old)),old);assert.throws(()=>startSecondChapterInquiry(newGame()));
 for(const bad of [{...old,flags:{...old.flags,c02QuestionText:'private'}},{...s,scene:'c02InquiryEnd'},{...s,scene:'c02QuestionDraft',flags:{...s.flags,c02InternalTopic:'flow'}},{...s,flags:{...s.flags,c02QuestionDisposition:'review'}}])assert.equal(decodeSave(JSON.stringify(bad)),null);
 const draft=advance(s,'access');assert.throws(()=>advance(draft,'dates'));const review=advance(draft,'procedure');assert.equal(decodeSave(JSON.stringify({...review,flags:{...review.flags,c02QuestionText:'altered'}})),null);
});
