import {recordDetails,canCompare,compareTimeline,comparisonResponse} from './investigation.mjs';
import {commitments,chapterPhases,chapterPhase,backgroundFor,characterFor} from './chapter-meta.mjs';
import {chapterResult,consequences} from './hearing.mjs';
import {chapterScenes,evidenceCatalog,taskCatalog} from './chapter.mjs';
import {newGame,advance,readNextPage,options,blockedReason,readSave,writeSave} from './engine.mjs';
import {openTitle,portrait} from './game.js';
const $=id=>document.getElementById(id);
let state=null;let storageAvailable=true;
try{state=readSave(localStorage,'auto');}catch{storageAvailable=false;}
function node(tag,text){const el=document.createElement(tag);el.textContent=text;return el;}
function button(text,action){const b=node('button',text);b.onclick=action;return b;}
function persist(slot='auto'){try{writeSave(localStorage,slot,state);$('storage-status').textContent=slot==='auto'?'進度已自動儲存。':`已儲存至欄位 ${slot}。`;return true;}catch{$('storage-status').textContent='此瀏覽器無法儲存。你仍可遊玩，但關閉頁面會失去未保存的進度。';storageAvailable=false;return false;}}
function title(){ $('continue-story').hidden=!state;$('new-story').textContent=state?'開始新第一章 →':'開始第一章 →';}
function open(){ $('title-screen').hidden=true;$('play-screen').hidden=true;$('chapter-screen').hidden=false;render();$('chapter-speaker').focus();}
function render(){const scene=chapterScenes[state.scene];const phase=chapterPhase(state);$('chapter-phases').replaceChildren(...chapterPhases.map((p,i)=>{const li=node('li',`${i+1}. ${p.label}`);if(i===phase)li.setAttribute('aria-current','step');return li;}));const art=backgroundFor(state.scene);$('chapter-background').hidden=!art;if(art){$('chapter-background').src=art;$('chapter-background').alt={'assets/office-day.png':'雨中港都辦公室','assets/hearing-room.png':'議會聽證室','assets/harbor-day.png':'南灣港候船區','assets/union-room.png':'工會休息室'}[art];}document.querySelector('#chapter-screen .stage').classList.toggle('has-art',Boolean(art));const sprite=characterFor(scene.speaker);$('chapter-portrait').classList.toggle('illustrated',Boolean(sprite));if(sprite){const image=document.createElement('img');image.src=sprite;image.alt='';$('chapter-portrait').replaceChildren(image);}else $('chapter-portrait').innerHTML=portrait(scene.portrait);$('chapter-location').textContent=scene.place;$('chapter-progress').textContent=scene.hub?`剩餘時段 ${state.slots} / 3`:scene.terminal?'第一章流程完成':'案件調查中';$('chapter-speaker').textContent=scene.speaker;$('chapter-role').textContent=scene.role;if((state.pageIndex||0)<(scene.beats?.length||0)){$('chapter-speaker').textContent='旁白';$('chapter-role').textContent='場景敘事';}if(scene.beats)$('chapter-progress').textContent+=` · 對話 ${(state.pageIndex||0)+1}/${scene.beats.length+1}`;$('chapter-text').textContent=[...(scene.beats||[]),scene.text][state.pageIndex||0];$('chapter-note').textContent=state.note;if(state.scene==='reconcile'&&comparisonResponse(state))$('chapter-note').textContent+=' '+comparisonResponse(state);$('chapter-choices').replaceChildren();if((state.pageIndex||0)<(scene.beats?.length||0)){$('chapter-choices').append(button('繼續閱讀 →',()=>{state=readNextPage(state);persist();render();$('chapter-speaker').focus();}));}else for(const c of options(state)){const reason=blockedReason(state,c);const b=button(c.text+(reason?`（${reason}）`:''),()=>{if(c.requires&&!confirm('此選擇將公開出示 '+c.requires.join('、')+'。請確認保留完整脈絡並遮蔽個資。取消可返回選項。'))return;state=advance(state,c.id);persist();render();$('chapter-speaker').focus();});b.disabled=Boolean(reason);$('chapter-choices').append(b);}if(canCompare(state))$('chapter-choices').append(button('比對原始時間線',()=>panel('investigation')));if(scene.terminal){const result=chapterResult(state);$('chapter-speaker').textContent=result.title;$('chapter-text').textContent=result.reason+' '+result.aftermath+' 第二章尚未製作。';$('chapter-note').replaceChildren(...consequences(state).map(line=>node('p',line)));}if(scene.terminal)$('chapter-choices').append(button('查看案件整理',()=>panel('evidence')),button('返回主畫面',openTitle));const labels={trust:'公共信任',autonomy:'本土自主',relations:'國際關係',tension:'危機程度'};$('chapter-stats').replaceChildren(...Object.entries(state.stats).map(([k,v])=>node('div',`${labels[k]}　${v}`)));if(!storageAvailable)$('storage-status').textContent='儲存不可用；目前進度僅保留在此頁面。';}
function panel(kind){const content=$('panel-content');content.replaceChildren();const names={investigation:'線索判讀 · 原始時間線',tasks:'任務簿',evidence:'證據簿',commitments:'承諾簿',relations:'人物關係',history:'對話紀錄',saves:'存檔／讀檔'};$('panel-title').textContent=names[kind];
if(kind==='investigation'){content.append(node('p','以下為你已取得的資料。船上時間與港口時間使用不同時鐘，請先校正。這項判讀不消耗行程、不改變公開授權，也不會重複增加數值。'));for(const id of ['E02','E03']){content.append(node('h3',`${id} · ${evidenceCatalog[id].title}`));const table=document.createElement('table');for(const row of recordDetails[id]){const tr=document.createElement('tr');for(const text of row)tr.append(node('td',text));table.append(tr);}content.append(table);}for(const [id,label] of [['sequence','偏航 → 通訊中斷 → 轉向 → 碰撞；動機未知'],['simultaneous','直接比原始時間，不需要校正'],['motive','時間順序足以證明蓄意挑釁']])content.append(button(label,()=>{state=compareTimeline(state,id);persist();render();panel('investigation');}));if(state.flags.timelineComparison)content.append(node('p',state.note+' '+comparisonResponse(state)));}
if(kind==='commitments'){content.append(node('p','目前為故事第 1 日。期限依故事時間計算，不是現實日期。第二章尚未製作，因此本章不會自動完成承諾。'));const items=commitments(state);if(!items.length)content.append(node('p','目前沒有已作出的期限或追蹤承諾。'));for(const item of items){const row=node('article','');row.className='evidence-card';row.append(node('h3',item.title),node('p',`${item.status}｜${item.due}`),node('p',`來源：${item.source}`),node('p',item.detail));content.append(row);}}
if(kind==='tasks'){const labels={pending:'待辦',active:'進行中',complete:'已完成',missed:'本次錯過'};for(const [id,title] of Object.entries(taskCatalog))content.append(node('p',`${labels[state.tasks[id]]}｜${title}`));}
if(kind==='evidence'){content.append(node('p','取得不等於核實；核實不等於獲准公開。授權均以遮蔽個資及完整脈絡為前提。'));if(!Object.keys(state.evidence).length)content.append(node('p','尚未取得證據。'));for(const [id,status] of Object.entries(state.evidence)){const item=node('article','');item.className='evidence-card';item.append(node('h3',`${id} · ${evidenceCatalog[id].title}`),node('p',`來源：${id==='E03'&&!state.visited.includes('technician')?'正式調查簡報（摘要）':evidenceCatalog[id].source}`),node('p',evidenceCatalog[id].summary),node('p',`${status.verified?'已核實':'未核實'} ／ ${status.authorized?'可依授權公開':'未獲公開授權'}`));if(recordDetails[id])for(const [time,text] of recordDetails[id])item.append(node('p',`${time}｜${text}`));content.append(item);}}
if(kind==='relations'){for(const [id,name] of Object.entries({yucheng:'林予澄',haining:'陳海寧',anhe:'許安禾'}))content.append(node('p',`${name}　${state.relations[id]>0?'+':''}${state.relations[id]}（−10 至 +10）`));content.append(node('p','關係值反映合作變化，不能替代證據或公開授權。'));}
if(kind==='history'){const current=chapterScenes[state.scene];if(current.beats){const entry=node('article','');entry.className='evidence-card';entry.append(node('h3',`${current.speaker} · 本場已讀`),node('p',[...current.beats,current.text].slice(0,(state.pageIndex||0)+1).join('\n\n')));content.append(entry);}if(!state.history.length&&!current.beats)content.append(node('p','尚未做出選擇。'));for(const h of state.history){const item=node('article','');item.className='evidence-card';item.append(node('h3',h.speaker),node('p',h.text),node('p',`你的選擇：${h.choice}`));content.append(item);}}
if(kind==='saves'){content.append(node('p','正式第一章使用獨立存檔，概念序章的原始進度會保留。讀檔會取代目前遊玩狀態。'));for(const slot of ['auto','1','2','3']){let saved=null;try{saved=readSave(localStorage,slot);}catch{}const row=node('article','');row.className='evidence-card';row.append(node('h3',slot==='auto'?'自動存檔':`手動欄位 ${slot}`),node('p',saved?`${chapterScenes[saved.scene].place} · 已做 ${saved.history.length} 次選擇`:'空白或不相容的存檔'));if(slot!=='auto')row.append(button('儲存',()=>{if(saved&&!confirm('要覆寫這個手動存檔嗎？'))return;if(persist(slot))panel('saves');}));const load=button('讀取',()=>{let fresh;try{fresh=readSave(localStorage,slot);}catch{}if(!fresh){$('storage-status').textContent='存檔無法讀取。';return;}if(!confirm('讀檔會取代目前進度，要繼續嗎？'))return;state=fresh;persist();$('case-panel').close();open();});load.disabled=!saved;row.append(load);content.append(row);}}
if(!$('case-panel').open)$('case-panel').showModal();}
$('new-story').onclick=()=>{if(state&&!confirm('開始新第一章會取代自動存檔，手動存檔仍保留。要繼續嗎？'))return;state=newGame();persist();open();};$('continue-story').onclick=()=>{if(state)open();};document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>panel(b.dataset.panel));$('close-panel').onclick=()=>$('case-panel').close();window.addEventListener('mist-title',title);window.addEventListener('mist-restart',()=>{if($('chapter-screen').hidden)return;if(confirm('重新開始第一章？手動存檔仍保留。')){state=newGame();persist();open();}});title();
