import test from 'node:test';import assert from 'node:assert/strict';import {accessFixture} from './scripts/chapter-two-followup-fixture.mjs';import {startSecondChapterReading,advance,options,blockedReason,decodeSave,newGame} from './engine.mjs';import {readingSummary} from './chapter-two-reading.mjs';import {publishedSupplement} from './chapter-two-public.mjs';import {commitments} from './chapter-meta.mjs';import {exportSave,importSave} from './save-transfer.mjs';import {recordPlayTime} from './playtime.mjs';import {ambienceFor} from './ambience.mjs';
test('384 reading routes enforce order and restricted notes, preserve source privacy and public snapshots',()=>{
 let count=0;for(const mode of ['verified','held','missing'])for(const published of [true,false])for(const accessAction of ['onsite','defer','appeal','split'])for(const sourceCheck of ['check','hold'])for(const accessNext of ['access','timeline']){
 const old=accessFixture({mode,published,accessAction,sourceCheck,accessNext,file:['onsite','defer'].includes(accessAction)?'public':'reasons'}),snapshot=JSON.stringify(old);
 for(let readChoice=0;readChoice<2;readChoice++)for(const dateChoice of ['compare','hold']){
 let s=startSecondChapterReading(old);assert.deepEqual(decodeSave(JSON.stringify(s)),s);for(const branch of accessNext==='access'?['reading','dates']:['dates','reading']){assert.equal(options(s).length,1);assert.equal(options(s)[0].id,branch);s=advance(s,branch);assert.deepEqual(decodeSave(JSON.stringify(s)),s);s=advance(s,branch==='reading'?options(s)[readChoice].id:dateChoice);assert.deepEqual(decodeSave(JSON.stringify(s)),s);}
 assert.equal(s.scene,'c02ReadingReport');s=advance(s,'record');assert.deepEqual(importSave(JSON.stringify(exportSave(s))),s);assert.deepEqual(s.evidence,s.flags.c02ReadResult==='read'?{...old.evidence,E10:{verified:true,authorized:false}}:old.evidence);if(s.evidence.E10)assert.match(blockedReason(s,{requires:['E10']}),/未獲公開授權/);assert.deepEqual(s.evidence.E09,{verified:false,authorized:false});assert.deepEqual(s.tasks,old.tasks);assert.deepEqual(s.stats,old.stats);assert.deepEqual(commitments(s),commitments(old));assert.deepEqual(publishedSupplement(s),publishedSupplement(old));assert.equal(s.flags.c02SentQuestions,old.flags.c02SentQuestions);assert.equal(s.scene,'c02ReadingEnd');assert.equal(recordPlayTime(s,1000,true),s);assert.equal(ambienceFor(s.scene),null);assert.throws(()=>startSecondChapterReading(s));assert.match(readingSummary(s)[1].status,dateChoice==='compare'?/已分列核對/:/尚未判定/);count++;
 }assert.equal(JSON.stringify(old),snapshot);}assert.equal(count,384);
});
test('old access saves continue; premature notes, unauthorized publication and reading without permission fail',()=>{
 const old=accessFixture({accessAction:'defer'}),s=startSecondChapterReading(old);assert.deepEqual(decodeSave(JSON.stringify(old)),old);assert.throws(()=>startSecondChapterReading(newGame()));
 for(const bad of [{...old,evidence:{...old.evidence,E10:{verified:true,authorized:false}}},{...s,scene:'c02ReadingEnd'},{...s,scene:'c02DateCrosscheck'},{...s,flags:{...s.flags,c02ReadResult:'read'},evidence:{...s.evidence,E10:{verified:true,authorized:false}}}])assert.equal(decodeSave(JSON.stringify(bad)),null);
 let read=advance(advance(startSecondChapterReading(accessFixture()),'reading'),'read');assert.equal(decodeSave(JSON.stringify({...read,evidence:{...read.evidence,E10:{verified:true,authorized:true}}})),null);
});
