import test from 'node:test';import assert from 'node:assert/strict';import {receptionFixture} from './scripts/chapter-two-followup-fixture.mjs';import {startSecondChapterProposal,advance,options,decodeSave,newGame} from './engine.mjs';import {proposalSummary,canJointDesk,proposalReaction} from './chapter-two-proposal.mjs';import {publishedSupplement} from './chapter-two-public.mjs';import {commitments} from './chapter-meta.mjs';import {recordPlayTime} from './playtime.mjs';import {ambienceFor} from './ambience.mjs';import {exportSave,importSave} from './save-transfer.mjs';
test('240 proposal routes enforce agenda order and joint desk prerequisites, preserve records and obligations',()=>{
 let count=0;for(const mode of ['verified','held','missing'])for(const published of [true,false])for(const caucus of ['coordinate','separate'])for(const conflict of ['recuse','delay'])for(const focus of ['boundaries','staffing']){
 const old=receptionFixture({mode,published,caucus,conflict,focus}),snapshot=JSON.stringify(old);
 for(const boundary of ['questions','closed'])for(const staffing of canJointDesk(old)?['independent','joint']:['independent'])for(const result of ['accept','revise']){
 let s=startSecondChapterProposal(old);const branches=focus==='boundaries'?['boundary','staff']:['staff','boundary'];assert.deepEqual(decodeSave(JSON.stringify(s)),s);
 for(const branch of branches){assert.equal(options(s).length,1);assert.equal(options(s)[0].id,branch);s=advance(s,branch);assert.deepEqual(decodeSave(JSON.stringify(s)),s);
 if(branch==='staff'){assert.equal(options(s).some(o=>o.id==='joint'),canJointDesk(old));if(!canJointDesk(old))assert.throws(()=>advance(s,'joint'));}s=advance(s,branch==='boundary'?boundary:staffing);assert.deepEqual(decodeSave(JSON.stringify(s)),s);}
 assert.equal(s.scene,'c02TermsReview');assert.match(proposalReaction(s),/草案待審閱/);s=advance(s,result);assert.equal(s.scene,'c02ProposalEnd');assert.deepEqual(importSave(JSON.stringify(exportSave(s))),s);assert.deepEqual(s.evidence,old.evidence);assert.deepEqual(s.tasks,old.tasks);assert.deepEqual(commitments(s),commitments(old));assert.deepEqual(publishedSupplement(s),publishedSupplement(old));assert.equal(s.stats.trust,old.stats.trust);assert.equal(s.stats.autonomy,Math.max(0,Math.min(100,old.stats.autonomy+(result==='accept'?(boundary==='questions'?1:-1):0))));assert.match(proposalSummary(s)[2].status,result==='accept'?/雙方已簽/:/未簽署/);assert.equal(recordPlayTime(s,1000,true),s);assert.equal(ambienceFor(s.scene),null);assert.throws(()=>startSecondChapterProposal(s));count++;
 }assert.equal(JSON.stringify(old),snapshot);}assert.equal(count,240);
});
test('old reception saves continue; premature outcomes, wrong order and unsupported joint seats are rejected',()=>{
 const old=receptionFixture({caucus:'separate'});assert.deepEqual(decodeSave(JSON.stringify(old)),old);assert.throws(()=>startSecondChapterProposal(newGame()));const s=startSecondChapterProposal(old);
 for(const bad of [{...old,flags:{...old.flags,c02ProposalOutcome:'limited'}},{...s,scene:'c02ProposalEnd'},{...s,scene:'c02StaffTerms'},{...s,flags:{...s.flags,c02StaffTerm:'joint'}},{...s,flags:{...s.flags,c02ProposalOutcome:'counter'}}])assert.equal(decodeSave(JSON.stringify(bad)),null);
});
