import {availableCorrections} from './corrections.mjs';
export const planMembers={player:'沈若川',yucheng:'林予澄'};
export function planJobs(s){return availableCorrections(s).filter(t=>s.flags['correction_'+t.id]==='ready').flatMap(t=>[{id:t.id+'_publish',title:t.title+' · 發布前核對',detail:'核對原問答、修正理由、資料授權與版本。這是發布前工作，尚未公開。'},{id:t.id+'_contact',title:t.title+' · 外部回覆',detail:'聯絡工會、記者或主管窗口，說明修正、限制與未完成事項。排程不等於已聯絡。'}]);}
export function planAssignments(s){return planJobs(s).filter(j=>s.flags['followup_'+j.id]).map(j=>({...j,member:s.flags['followup_'+j.id]}));}
export function validFollowupPlan(s){const f=s.flags;if(f.followupConfirmed!==undefined&&typeof f.followupConfirmed!=='boolean')return false;const entries=Object.entries(f).filter(([k])=>k.startsWith('followup_'));return entries.length<=2&&entries.every(([k,v])=>planJobs(s).some(j=>'followup_'+j.id===k)&&Object.hasOwn(planMembers,v))&&new Set(entries.map(([,v])=>v)).size===entries.length&&(!f.followupConfirmed||entries.length>0);}
export function assignFollowup(s,id,member){if(s.scene!=='postStaff'||s.flags.followupConfirmed||!planJobs(s).some(j=>j.id===id)||!Object.hasOwn(planMembers,member))throw new Error('目前不能安排此工作');if(planAssignments(s).some(j=>j.member===member&&j.id!==id))throw new Error('每人只有一個後續工作時段');const next=structuredClone(s);next.flags['followup_'+id]=member;return next;}
export function resetFollowup(s){if(s.scene!=='postStaff'||s.flags.followupConfirmed)throw new Error('目前不能重排');const next=structuredClone(s);for(const k of Object.keys(next.flags))if(k.startsWith('followup_'))delete next.flags[k];return next;}
export function confirmFollowup(s){if(s.scene!=='postStaff'||s.flags.followupConfirmed||!planAssignments(s).length||!validFollowupPlan(s))throw new Error('請先安排有效工作');const next=structuredClone(s);next.flags.followupConfirmed=true;next.history.push({scene:s.scene,speaker:'林予澄',text:'你與予澄各有一個後續工作時段；發布核對與外部聯絡分開安排，未分配工作保留待辦。',choice:planAssignments(s).map(j=>`${planMembers[j.member]}：${j.title}`).join('；')});next.note='後續責任已確認；未安排工作仍待辦，稿件尚未發布，聯絡尚未完成。';return next;}
export function followupPlanSummary(s){if(!planJobs(s).length)return '';const assigned=planAssignments(s);return [...assigned.map(j=>`${s.flags.followupConfirmed?'已確認':'暫排'}｜${planMembers[j.member]}：${j.title}（待執行）`),...planJobs(s).filter(j=>!assigned.some(a=>a.id===j.id)).map(j=>`未安排｜${j.title}`)].join('\n\n');}
