import {initialStats,scenes,applyChoice,ending} from './story.mjs';
const $=id=>document.getElementById(id);let state={index:0,stats:{...initialStats},note:''};
try{const saved=JSON.parse(localStorage.getItem('mist-rpg'));if(saved&&Number.isInteger(saved.index)&&saved.index>=0&&saved.index<=scenes.length&&Object.keys(initialStats).every(k=>Number.isFinite(saved.stats?.[k])&&saved.stats[k]>=0&&saved.stats[k]<=100))state=saved;}catch{}
const colors={aide:'#56766c',worker:'#a08057',senior:'#454b62',diplomat:'#687081',host:'#79586b'};
export function portrait(kind){const color=colors[kind]||colors.aide;return `<svg viewBox="0 0 270 360" xmlns="http://www.w3.org/2000/svg"><path d="M35 360v-58q4-59 65-76h70q65 17 65 76v58" fill="${color}"/><path d="M107 218v32l28 25 28-25v-32" fill="#c1957d"/><path d="m99 234 36 41-25 46-27-76m87-11-35 41 25 46 27-76" fill="#d8d9cb"/><path d="m135 275-12 85h27z" fill="#253a3e"/><ellipse cx="135" cy="148" rx="58" ry="78" fill="#d5ac90"/><path d="M77 151q-24-102 56-107 82-5 65 107l-17-54q-49 17-71-8l-28 62" fill="#253037"/><path d="M104 153h18m28 0h18" stroke="#3e3936" stroke-width="4" stroke-linecap="round"/><path d="m133 158-5 25h12m-20 18q15 8 29-1" fill="none" stroke="#946951" stroke-width="3" stroke-linecap="round"/><path d="M38 355h194" stroke="#c4b382" opacity=".5"/></svg>`;}
function save(){try{localStorage.setItem('mist-rpg',JSON.stringify(state));}catch{}}
function render(){const labels={trust:'公共信任',autonomy:'本土自主',relations:'國際關係',tension:'危機程度'};$('stats').innerHTML=Object.entries(state.stats).map(([k,v])=>`<div class="stat">${labels[k]}<b>${v}</b><div class="bar"><i style="width:${v}%"></i></div></div>`).join('');$('choices').replaceChildren();$('feedback').textContent=state.note||'';if(state.index===scenes.length){const e=ending(state.stats);$('location').textContent='序章終章 · 明天仍將到來';$('progress').textContent='CHAPTER COMPLETE';$('speaker').textContent=e.title;$('role').textContent='你的序章結局';$('text').textContent=e.text;$('portrait').innerHTML=portrait('aide');addButton('再次探索另一條路',reset);return;}const scene=scenes[state.index];$('location').innerHTML='';$('location').append(document.createTextNode(scene.chapter),document.createElement('br'),document.createTextNode(scene.place));$('progress').textContent=`0${state.index+1} / 0${scenes.length}`;$('speaker').textContent=scene.speaker;$('role').textContent=scene.role;$('text').textContent=scene.text;$('portrait').innerHTML=portrait(scene.portrait);scene.choices.forEach((choice,i)=>addButton(choice.text,()=>{state.stats=applyChoice(state.stats,choice.effect);state.note=choice.note;state.index++;save();render();},i+1));}
function addButton(text,action,n){const b=document.createElement('button');if(n){const s=document.createElement('span');s.textContent=`0${n}`;b.append(s);}b.append(document.createTextNode(text));b.onclick=action;$('choices').append(b);}
function reset(){state={index:0,stats:{...initialStats},note:''};save();render();}render();

function openStory(){ $('title-screen').hidden=true; $('play-screen').hidden=false; render(); $('speaker').tabIndex=-1; $('speaker').focus(); }
export function openTitle(){ $('title-screen').hidden=false; $('play-screen').hidden=true; $('chapter-screen').hidden=true; window.dispatchEvent(new Event('mist-title')); }
$('legacy-story').onclick=openStory;
$('home').onclick=openTitle;
$('restart').onclick=()=>{if(!$('play-screen').hidden){if(confirm('要重新開始序章嗎？目前進度將被取代。'))reset();}else window.dispatchEvent(new Event('mist-restart'));};
openTitle();
