import {caucusReaction} from './caucus.mjs';
const c=(id,text,next,effects={},extra={})=>({id,text,next,effects,...extra});
export const hearingScenes={
 caucus:{place:'議會 · 黨團會議室',speaker:'周岳',role:'資深議員',portrait:'senior',text:'周岳把一份草案推到你面前。「臨時管制可以阻止謠言，但這一條連批評政府都可能算進去。」他停頓了一下。「維護公司的地方活動贊助也會被問到。你可以要求查合約，但不能在沒有證據時替任何人定罪。黨團需要合作，你要給我們什麼界線？」',choices:[c('amend','支持限時措施，但加入司法審查與公開報告。','diplomacy',{flags:{emergencyBill:'amend'},stats:{trust:3},note:'周岳接受提出修正；是否通過仍取決於後續表決。'}),c('reject','反對原案，以查證與公開資訊回應危機。','diplomacy',{flags:{emergencyBill:'reject'},stats:{autonomy:3,tension:2},note:'你拒絕原案，失去部分黨團協商支持。'}),c('accept','接受原案，先確保危機期間的行政效率。','diplomacy',{flags:{emergencyBill:'accept'},stats:{trust:-3,tension:3},note:'黨團願意提供協商資源；資訊權利的疑慮仍在。'})]},
 diplomacy:{place:'代表處 · 視訊通話',speaker:'艾琳・維爾',role:'西陸共同體外交代表',portrait:'diplomat',text:'「海西願意分享航道資訊，旭輪的救援團正在待命。我們可以協助獨立調查。」艾琳看著螢幕上的合約。「有限保密能讓資料更快交付，卻也會讓你更難說明合作條件。群島如何保留自主，不只是一句聲明。你願意讓誰監督？」',choices:[c('oversight','合作須受議會監督，公開條件與定期報告。','hearing1',{flags:{foreignTerms:'oversight'},stats:{relations:3,autonomy:3},tasks:{M03:'active'},note:'合作進度放慢；你承諾提出公開報告。'}),c('confidential','接受限期保密，保留議會閉門審查。','hearing1',{flags:{foreignTerms:'confidential'},stats:{relations:5,trust:-2},tasks:{M03:'active'},note:'外部資訊可較快交付，公開內容仍有限制。'}),c('rescue','先接受民間救援合作，不交換政治承諾。','hearing1',{flags:{foreignTerms:'rescue'},stats:{relations:2,tension:-3},tasks:{M03:'active'},note:'救援窗口建立，調查資訊仍需自行補足。'})]},
 hearing1:{place:'議會公開聽證 · 第一問',speaker:'許知言',role:'聽證直播主持人',portrait:'host',text:'「是不是蓄意挑釁？你早上的發言已經被不同陣營剪成短片。現在請說明：你能證明事故順序，還是已經能判定動機？」桌上的證據簿可以隨時查看。公開出示必須同時具備核實與授權。',choices:[c('timeline','出示 E02＋E03：還原順序，但不判定政治動機。','hearing2',{flags:{hearingAnswer:'timeline'},stats:{trust:4},note:'時間線完整出示，個資已遮蔽；你明確保留動機判斷。'},{requires:['E02','E03']}),c('defer','資料尚不宜公開，請獨立調查並承諾補件。','hearing2',{flags:{hearingAnswer:'defer'},note:'你沒有越過授權，聽證要求後續補件。'}),c('party','採用黨團說法，只強調對群島有利的部分。','hearing2',{flags:{hearingAnswer:'party'},stats:{trust:-4},note:'主持人追問被省略的拖船失誤，工會對此不滿。'}),c('clip','出示十秒影片，宣稱足以證明蓄意挑釁。','clarify1',{note:'主持人指出：影片來源未明，也沒有碰撞前的脈絡。你有一次澄清機會。'})]},
 clarify1:{place:'議會公開聽證 · 澄清機會',speaker:'許知言',role:'聽證直播主持人',portrait:'host',text:'「轉向不等於動機。請更正你的說法，或說明你為何仍要堅持。」澄清不會抹去剛才的發言，但能避免錯誤成為你的正式結論。',choices:[c('correct','收回動機指控，交由獨立調查。','hearing2',{flags:{hearingAnswer:'defer',correctedAccusation:true},stats:{trust:-1},note:'你更正了指控，仍需補交可公開的時間線。'}),c('insist','不更正，堅持這就是政治挑釁。','hearing2',{flags:{hearingAnswer:'accusation',unsupportedClaim:true},stats:{trust:-5,tension:5},note:'沒有支持動機的證據；你的正式指控留在聽證紀錄。'})]},
 hearing2:{place:'議會公開聽證 · 第二問',speaker:'周岳',role:'聽證委員',portrait:'senior',text:'「現在談港口自己的責任。維護缺失是否長期存在？外包公司的地方活動贊助，和這次事故有什麼可證明的關係？」你可以要求查合約，也可以承認資料不足。缺失與貪污是不同的指控。',choices:[c('contract','出示 E04：要求合約調查，不預判賄賂。','hearing3',{flags:{maintenanceAnswer:'contract'},stats:{trust:3},note:'維護缺失納入調查；政治贊助與事故的關聯尚待查明。'},{requires:['E04']}),c('briefing','依公開通訊簡報要求檢修，合約另外調查。','hearing3',{flags:{maintenanceAnswer:'briefing'},note:'你依已知故障要求檢修，不把未知關聯當成結論。'},{requires:['E03']}),c('bribery','直接指控：有政治贊助就一定存在賄賂。','clarify2',{note:'委員要求提出金流與對價證據；目前資料無法支持。'})]},
 clarify2:{place:'議會公開聽證 · 澄清機會',speaker:'周岳',role:'聽證委員',portrait:'senior',text:'「你可以查我們，也必須讓調查有標準。贊助本身不能證明對價。」會議室安靜下來。你要把這句話留作指控，還是把疑點交給可檢驗的調查？',choices:[c('correct','更正為要求調查，不宣稱賄賂已成立。','hearing3',{flags:{maintenanceAnswer:'investigate',correctedBribery:true},stats:{trust:-1},note:'委員記錄了更正與合約調查要求。'}),c('insist','拒絕更正，堅持貪污已經成立。','hearing3',{flags:{maintenanceAnswer:'accusation',unsupportedClaim:true},stats:{trust:-5,tension:5},note:'證據不足的指控寫入正式紀錄，後續將要求你回應。'})]},
 hearing3:{place:'議會公開聽證 · 第三問',speaker:'許知言',role:'聽證直播主持人',portrait:'host',text:'「你如何讓船員安全回去工作？又如何避免臨時措施成為永久權力？」這一次不能只說會努力。請提出措施，也說清楚誰來監督、何時報告。',choices:[c('safety','要求設備檢修、透明救助，七日內公開進度。','night',{flags:{safetyPlan:'report'},stats:{trust:3},tasks:{M03:'complete'},note:'新增七日報告承諾；救助預算仍須審議。'}),c('inquiry','優先獨立調查，提出檢修時程與臨時救助窗口。','night',{flags:{safetyPlan:'inquiry'},stats:{tension:-2},tasks:{M03:'complete'},note:'你提出調查、檢修與救助安排，沒有保證尚未通過的資金。'})]},
 night:{place:'辦公室 · 聽證之後',speaker:'林予澄',role:'幕僚長',portrait:'aide',text:'燈還亮著，電話卻終於少了。予澄把聽證紀錄與今天的承諾放在同一張桌上。「結果不是今晚的掌聲。明天誰還願意把資料交給我們，下週誰真的拿到幫助，才是這一章留下的東西。」',choices:[c('review','整理聽證結果與待履行的承諾。','postUnion')]},
 chapterEnd:{place:'第一章 · 案件階段結算',speaker:'沈若川',role:'本土協進黨議員',portrait:'senior',text:'第一章的決策流程已完成。事故責任與政治關聯仍需正式調查；第二章尚未製作。',terminal:true,choices:[]}
};
export function chapterResult(state){const f=state.flags;if(f.unsupportedClaim)return {id:'storm',title:'失控的聽證',reason:'你在獲得澄清機會後，仍堅持現有證據不支持的動機或賄賂指控。',aftermath:'危機升高；下一章需要回應指控並修復合作關係。'};if(f.hearingAnswer==='party')return {id:'party',title:'黨團的版本',reason:'你以選擇性說法回應聽證，省略了拖船的失誤。',aftermath:'黨團願意協助協商，工會與公眾仍要求完整說明。'};if(f.hearingAnswer==='timeline'&&['E02','E03'].every(k=>state.evidence[k]?.verified&&state.evidence[k]?.authorized))return {id:'credible',title:'可信的時間線',reason:'你以核實且獲授權的資料還原順序，並保留對政治動機的判斷。',aftermath:'時間線納入紀錄；維護責任與政治關聯仍待正式調查。'};return {id:'pending',title:'未完成的調查',reason:'你保留了未能公開證明的部分，或更正了先前的錯誤指控。',aftermath:'聽證要求補件；你沒有因資料限制而失去繼續調查的機會。'};}
export function consequences(state){const f=state.flags;const notes=[];const negotiation=caucusReaction(state,'chapterEnd');if(negotiation)notes.push(negotiation);
if(f.emergencyBill==='amend')notes.push('管制草案：提出限期、司法審查與公開報告修正；尚未表決。');if(f.emergencyBill==='reject')notes.push('管制草案：反對原案，需另尋跨黨合作。');if(f.emergencyBill==='accept')notes.push('管制草案：接受原案，行政效率與權利疑慮將繼續受到追問。');
if(f.foreignTerms==='oversight')notes.push('外交合作：受議會監督，待提交公開合作報告。');if(f.foreignTerms==='confidential')notes.push('外交合作：限期保密與閉門審查，公開範圍受到限制。');if(f.foreignTerms==='rescue')notes.push('外交合作：先建立民間救援窗口，調查仍需自行補足。');
if(f.reliefPromise==='report'||f.safetyPlan==='report')notes.push('待履行：七日內回報檢修與救助進度（第二章追蹤，尚未履行）。');else notes.push('待履行：確認檢修時程與救助轉介結果。');
if(f.aideDelegation==='delegate')notes.push('幕僚：予澄可安排分工並追蹤承諾。');if(f.aideDelegation==='centralize')notes.push('幕僚：決策集中於你，團隊提醒注意工作瓶頸。');
if(state.evidence.E02?.authorized)notes.push('工會：公開授權仍以完整脈絡與個資保護為條件。');else notes.push('工會：航行紀錄尚未獲公開授權，只能供調查使用。');return notes;}
