import test from 'node:test';import assert from 'node:assert/strict';
import {newGame,advance,options,blockedReason,validState,decodeSave} from './engine.mjs';
import {chapterResult,consequences} from './hearing.mjs';
const go=(s,...ids)=>ids.reduce((state,id)=>advance(state,id),s);
function checkpoint({tech=true,authorized=true}={}){let s=go(newGame(),'stance','depart','listen','respect','review','schedule');s=tech?go(s,'technician','protect','family','process','aide','delegate'):go(s,'family','refer','journalist','written','aide','delegate');return go(s,'bounded',authorized?'authorize':'private');}
const hearing=(cfg)=>go(checkpoint(cfg),'continue','amend','oversight');
test('Every hearing route finishes, four outcomes are reachable across all evidence setups',()=>{const outcomes=new Set();let leaves=0;for(const tech of [true,false])for(const authorized of [true,false]){function walk(s){assert.ok(validState(s));if(s.scene==='chapterEnd'){assert.equal(s.tasks.M03,'complete');assert.ok(s.flags.emergencyBill&&s.flags.foreignTerms&&s.flags.safetyPlan);outcomes.add(chapterResult(s).id);leaves++;return;}const choices=options(s).filter(c=>!blockedReason(s,c));assert.ok(choices.length);for(const c of choices)walk(advance(s,c.id));}walk(checkpoint({tech,authorized}));}assert.deepEqual([...outcomes].sort(),['credible','party','pending','storm']);assert.equal(leaves,(360+288+270+216)*8);});
test('Unauthorized evidence cannot be used, and blocked attempt does not mutate state',()=>{const s=hearing({authorized:false});assert.match(blockedReason(s,options(s)[0]),/未獲公開授權/);const before=JSON.stringify(s);assert.throws(()=>advance(s,'timeline'),/未獲公開授權/);assert.equal(JSON.stringify(s),before);});
test('Missing maintenance document still permits hearing via public briefing',()=>{const s=go(hearing({tech:false}),'timeline');assert.match(blockedReason(s,options(s).find(c=>c.id==='contract')),/尚未取得/);const end=go(s,'briefing','inquiry','review','repair','transparent','prioritize');assert.equal(chapterResult(end).id,'credible');});
test('Correcting unsupported claims avoids storm, refusal overrides other answers',()=>{const corrected=go(hearing(),'clip','correct','bribery','correct','safety','review','repair','transparent','prioritize');assert.equal(chapterResult(corrected).id,'pending');const refused=go(hearing(),'timeline','bribery','insist','safety','review','repair','transparent','prioritize');assert.equal(chapterResult(refused).id,'storm');const party=go(hearing(),'party','briefing','safety','review','repair','transparent','prioritize');assert.equal(chapterResult(party).id,'party');});
test('Old checkpoint save resumes and commitments persist through save/reload',()=>{const old=checkpoint();const loaded=decodeSave(JSON.stringify(old));assert.ok(loaded);const end=go(loaded,'continue','reject','rescue','timeline','contract','safety','review','repair','transparent','prioritize');const restored=decodeSave(JSON.stringify(end));assert.deepEqual(restored,end);assert.equal(restored.flags.emergencyBill,'reject');assert.equal(restored.flags.foreignTerms,'rescue');assert.ok(consequences(restored).some(x=>x.includes('七日')));assert.equal(restored.flags.aideDelegation,'delegate');});
