export function mediaTopics(s){return [
 {key:'mediaAid',title:'外援條件怎麼說',question:s.flags.foreignTerms==='rescue'?'予澄把民間救援窗口寫在第一行。「窗口建立不等於隊伍抵達。記者會問，海西分析與共同聲明是否一起接受了？」':'予澄把合作條件分成已選立場與待談附件。「記者會問你拿什麼換外援。不能把提出監督要求說成伙伴已經同意。」',choices:[{id:'limits',text:'分列協商立場、未決條件與尚未交付的援助。',reply:'予澄保留不確定欄位，提醒你準備說明延誤的代價。這是答問稿，還沒有對外發布。'},{id:'secured',text:'用「已確保外援與自主」作為答問主軸。',reply:'予澄畫掉「已確保」旁的勾號。「援助沒交付，附件沒談完。這句話若照稿說出，就需要回應保證從哪裡來。」她保留草稿分歧。'}]},
 {key:'mediaConflict',title:'黨團贊助與調查邊界',question:s.flags.caucusConflict==='delay'?'予澄翻開暫緩調閱名冊的紀錄。「記者若問你是否用調查範圍換人手，你要說明自己的取捨，還是只說相信黨團？」':'予澄提醒，利益申報與迴避即使提出，也不等於金流已查清。「記者問周岳的贊助時，我們能指出程序，不能替他宣布沒有問題。」',choices:[{id:'account',text:'說明申報、調閱與資源取捨，保留未知金流。',reply:'予澄要求把未調閱事項留下；承認調查限制可能招來批評，但沒有把未知贊助關係寫成結論。'},{id:'clear',text:'強調黨團已自清，不再談贊助疑點。',reply:'「我們手上沒有完成自清的調查。」予澄把這句標成待修正，提醒你不能用合作關係代替金流核對。'}]},
 {key:'mediaPrivacy',title:'記者索取原件時',question:'模擬提問卡寫著：「為什麼不能把原始航行紀錄全部放上網？你是否替船員掩蓋失誤？」予澄請你同時回答查核需求與來源保護，而不是只說相信我們。',choices:[{id:'method',text:'提供核對方法與可公開範圍，原件另按授權處理。',reply:'予澄要求列出原始時間、校正步驟與遮蔽原因。方法說明不會擴大公開或跨境授權，也不會自動發布文件。'},{id:'release',text:'承諾聽證後公開全部原件，以示沒有隱瞞。',reply:'予澄拒絕安排上傳。「你不能替來源同意，姓名與完整紀錄也不是同一項授權。」草稿中的過量承諾留作待更正，原件未公開。'}]}
];}
export function answerMediaPrep(s,key,id){const t=mediaTopics(s).find(t=>t.key===key),c=t?.choices.find(c=>c.id===id);if(s.scene!=='hearing1'||!c||s.flags[key])throw new Error('目前無法重作媒體準備');const n=structuredClone(s);n.flags[key]=id;n.note=c.reply;n.history.push({scene:s.scene,speaker:'林予澄',text:t.question,choice:c.text+'\n'+c.reply});return n;}
export function mediaChallenge(s){if(!['mediaAid','mediaConflict','mediaPrivacy'].some(k=>s.flags[k]))return '';const lines=['許安禾看過你交給採訪窗口的答問方向，要求確認哪些只是草稿、哪些已在聽證說出。草稿不會被當作你已公開發言的證據。'];if(s.flags.mediaAid==='secured')lines.push('「你準備稿寫已確保外援，交付與附件卻還沒確定。現在會把這句留在正式回覆裡嗎？」');if(s.flags.mediaConflict==='clear')lines.push('「金流沒有核對，為什麼準備說黨團已自清？」');if(s.flags.mediaPrivacy==='release')lines.push('「公開全部原件這句是否取得來源同意？請先確認範圍。」');if(s.flags.mediaAid==='limits'&&s.flags.mediaConflict!=='clear'&&s.flags.mediaPrivacy!=='release')lines.push('「限制列得清楚，但何時能補上答案？請留待辦，不要把承認未知當成不必追蹤。」');if(s.flags.reporterSource==='bargain')lines.push('安禾維持先前暫停聯合訪談的立場，只以書面詢問；本次答覆不會自動修復合作。');return lines.join('\n\n');}
export function answerMediaChallenge(s,id){if(s.scene!=='postPress'||!mediaChallenge(s)||s.flags.mediaReply||!['clarify','defend'].includes(id))throw new Error('目前無法回答媒體追問');const n=structuredClone(s);n.flags.mediaReply=id;n.note=id==='clarify'?'你提交限定範圍的書面回覆：草稿不等於已完成成果，未決條件列待辦；原件仍依授權處理。回覆已記錄，稿件尚未刊登。':'你要求沿用原答問方向。安禾保留對未完成成果與授權範圍的追問，沒有把你拒絕修改當成證據已成立。';n.history.push({scene:s.scene,speaker:'許安禾',text:mediaChallenge(s),choice:(id==='clarify'?'釐清草稿與成果，列出待辦。':'維持原稿方向，不補充限制。')+'\n'+n.note});return n;}
export function mediaReaction(s,scene){const f=s.flags;if(['hearing1','hearing3'].includes(scene)&&mediaChallenge(s))return '予澄保留答問草稿：外援、調查與公開資料仍須逐項確認；準備稿不等於正式發言或證據。';if(['postStaff','chapterEnd'].includes(scene)&&f.mediaReply)return f.mediaReply==='clarify'?'媒體回覆：已釐清草稿與成果、保留未決事項；刊登、援助與調查仍待進展。':'媒體回覆：維持原稿方向；安禾對成果保證與資料範圍的疑問仍未解決。';return '';}
