import {planMembers,planJobs,planAssignments} from './followup-plan.mjs';
export function canDiscussPlan(s){return s.scene==='postStaff'&&s.flags.followupConfirmed===true&&planAssignments(s).length>0;}
export function meetingDialogue(s){if(!s.flags.followupConfirmed)return [];const assigned=planAssignments(s);const jobs=planJobs(s);const lines=['予澄把確認過的排程留在桌上，另放一張空白紙。「我們說誰會做，還沒有說誰在等。今晚不是再確認一次名字，是決定怎麼對待還沒有接到回覆的人。」'];
for(const j of assigned){if(j.member==='player')lines.push(j.id.endsWith('_publish')?`你接下${j.title}。予澄問：「簽名之前，原問題與修正稿都會放在一起嗎？你自己核對，也要留下別人能追的版本；議員簽名不能替代資料授權。」`:`你接下${j.title}。予澄問：「如果窗口沒有新答案，你會照樣回覆嗎？親自聯絡不是只等好消息，有時要讓對方知道，今天還不能答應什麼。」`);else lines.push(j.id.endsWith('_publish')?`予澄接下${j.title}。「我可以核對版本與限制；涉及你的正式更正，仍要你確認原發言。授權不在稿件裡自動產生，我也不能替你把未知簽成已查明。」`:`予澄接下${j.title}。「我會記下收件、回覆與對方的新問題。聯絡過不是同意過，沒有得到答案，也不能在清單寫成雙方已達共識。」`);}
const missing=jobs.filter(j=>!assigned.some(a=>a.id===j.id));if(missing.length)lines.push(`未安排的工作仍有${missing.length}項。予澄指向第一項「${missing[0].title}」：「不是沒有人在乎，是現在沒有時段。把它留在表上，才有人知道需要改約或另找窗口；藏起來就只剩對方繼續等。」`);
const reserved=Object.keys(s.flags).filter(k=>k.startsWith('draftReview_')&&s.flags[k]==='reserve');if(reserved.some(k=>k.startsWith('draftReview_union_')))lines.push('海寧的異議仍附在稿件旁。予澄提醒，保留原稿是你的選擇，工會的不認同也是紀錄的一部分。「回覆時請先說明分歧在哪裡，不能用已審閱三個字替他改成支持。」');if(reserved.some(k=>k.startsWith('draftReview_press_')))lines.push('知言要求保留的異議也沒有消失。予澄把原問答和稿件版本一起列入聯絡附件。「她核對過，不表示她替我們背書。下一次追問很可能從這個分歧開始。」');if(!reserved.length&&Object.keys(s.flags).some(k=>k.startsWith('draftReview_')&&s.flags[k]==='incorporate'))lines.push('已納入的審閱意見不保證每個人滿意。予澄說，這只是讓對方能看出哪些限制進了稿件，接下來仍要核對發布版本與實際回覆。');
if(!Object.keys(s.flags).some(k=>k.startsWith('draftReview_')))lines.push('這些稿件尚未經工會或記者審閱。予澄把外部核對留在待辦，提醒不能用內部排程冒充對方已看過。');
lines.push('你問，如果先不談人力限制，會不會比較容易讓今晚結束。予澄沒有立即回答，只把空白紙轉向你：「我們可以調整時段。需要等的人要不要知道，這是你今晚還能決定的事。」');return lines;}
export function chooseMeetingReply(s,id){if(!canDiscussPlan(s)||s.flags.meetingReply||!['notify','hide'].includes(id))throw new Error('目前不能回答夜間排程討論');const next=structuredClone(s);next.flags.meetingReply=id;next.relations.yucheng=Math.max(-10,Math.min(10,next.relations.yucheng+(id==='notify'?1:-1)));next.note=id==='notify'?'你承諾告知等待者後續安排、限制與改約需求；尚未完成聯絡。':'你暫不說明人力限制；未安排工作與對方等待仍保留。';next.history.push({scene:s.scene,speaker:'林予澄',text:meetingDialogue(s).join('\n\n'),choice:(id==='notify'?'明日告知安排、限制與改約需求。':'先不對外說明，等待工作有結果再回覆。')+'\n'+next.note});return next;}
export function meetingReaction(s){return s.flags.meetingReply==='notify'?'夜間討論：你承諾明日告知等待者後續安排、限制與改約需求，聯絡仍待執行。':s.flags.meetingReply==='hide'?'夜間討論：你選擇暫不說明人力限制，予澄保留未安排工作與等待風險。':'';}
