export const initialStats={trust:50,autonomy:50,relations:50,tension:30};
export const scenes=[
{chapter:'序章 · 第一日 07:40',place:'霧海市 · 競選辦公室',speaker:'林予澄',role:'你的幕僚長',portrait:'aide',text:'港口昨夜發生碰撞。赤原聯盟說是我們刻意挑釁，海西聯邦要求我們保持克制。網路上那段影片已經傳遍了，但沒有人看過完整版本。議員，第一場記者會就在二十分鐘後。',choices:[{text:'先到港口，聽當事人怎麼說。',effect:{trust:12,tension:-4},note:'你延後記者會，讓查證走在聲量前面。'},{text:'公開表明：群島的未來由群島人民決定。',effect:{autonomy:12,tension:8},note:'你的立場迅速傳開，也引來更強烈的外交反應。'},{text:'先聯繫外國代表，確認各方掌握的資訊。',effect:{relations:12,trust:-4},note:'外交管道打開了，但選民希望你先回應他們。'}]},
{chapter:'序章 · 第一日 10:15',place:'南灣港 · 候船室',speaker:'陳海寧',role:'港口工會代表',portrait:'worker',text:'每次出事，大家都在談國家，卻沒人問我們明天能不能出海。那段影片只有最後十秒。我有完整的紀錄，但裡面也有我們船員犯錯的地方。你願意把整件事說清楚嗎？',choices:[{text:'公布完整紀錄，同時保護船員個資。',effect:{trust:15,autonomy:-3,tension:-5},note:'完整紀錄支持群島的部分說法，也揭露了自身疏失。'},{text:'先請獨立調查團核實，承諾公開期限。',effect:{trust:8,relations:6},note:'工會同意交出紀錄，要求你履行公開承諾。'},{text:'先公開有利片段，避免立場被削弱。',effect:{autonomy:8,trust:-15,tension:10},note:'支持者為你喝采，但工會開始懷疑你的誠意。'}]},
{chapter:'序章 · 第一日 14:30',place:'議會 · 黨團會議室',speaker:'周岳',role:'本土協進黨資深議員',portrait:'senior',text:'你的理想我懂。但今晚的節目會把我們每一句話都放大。黨團希望你支持港口緊急管制案，限制未經核實的消息。問題是，這個草案連批評政府都可能算進去。你要怎麼投？',choices:[{text:'提出期限與司法審查，否則不支持。',effect:{trust:10,autonomy:5,tension:-3},note:'你爭取到修正條文，也得罪了黨內強硬派。'},{text:'反對草案，支持公開查證與媒體自主。',effect:{trust:12,autonomy:7,relations:-3},note:'公民團體支持你的決定，黨團關係卻更加緊繃。'},{text:'先服從黨團，危機過後再修法。',effect:{autonomy:5,trust:-12,tension:6},note:'黨團給你更多資源，但改革承諾成為新的疑問。'}]},
{chapter:'序章 · 第一日 17:50',place:'西陸共同體 · 代表處',speaker:'艾琳・維爾',role:'西陸共同體外交代表',portrait:'diplomat',text:'海西聯邦願意提供航道情報，旭輪國提出海上救援演習。我們則願意支持獨立調查。但每一份合作都有條件。你希望群島在這些關係裡，保有什麼？',choices:[{text:'合作須公開，由議會監督，保留自主決策。',effect:{relations:8,autonomy:10,trust:5},note:'談判變慢了，但合作開始有清楚的界線。'},{text:'優先取得安全承諾，接受暫時的保密協議。',effect:{relations:15,autonomy:-10,tension:5},note:'外部支援增加，你卻必須面對監督不足的質疑。'},{text:'先推動民間救援合作，降低對抗訊號。',effect:{relations:8,tension:-12,autonomy:-3},note:'救援合作取得進展，部分選民認為你過於溫和。'}]},
{chapter:'序章 · 第一日 20:00',place:'公共電視 · 現場辯論',speaker:'許知言',role:'《島嶼之間》主持人',portrait:'host',text:'議員，今天你同時面對黨內壓力、外國條件與選民的不安。如果堅持本土自主會付出代價，你憑什麼要求人民相信你？',choices:[{text:'自主也包含知情權。我會公開證據與決策代價。',effect:{trust:12,autonomy:6,tension:-4},note:'你把承諾交給公眾檢驗，而非要求無條件信任。'},{text:'我們願意合作，但不把自己的未來交給任何強權。',effect:{autonomy:15,relations:-5,tension:5},note:'你的宣言凝聚了支持者，也提高了後續談判難度。'},{text:'讓生活回到正常，就是我現在最重要的責任。',effect:{trust:6,relations:6,tension:-10},note:'務實的承諾安撫了不安，也留下路線上的辯論。'}]}
];
export function applyChoice(stats,effect){return Object.fromEntries(Object.entries(stats).map(([key,value])=>[key,Math.max(0,Math.min(100,value+(effect[key]||0)))]));}
export function ending(s){if(s.trust>=80&&s.autonomy>=60)return {title:'把未來交還人民',text:'你以透明與自主建立新的支持。工會、公民團體與年輕選民開始加入你的團隊。下一章，你將面對黨內初選，而今天做出的承諾，會成為他們衡量你的標準。'};if(s.tension>=55)return {title:'風暴中的旗手',text:'你的立場成為危機中的鮮明旗幟。但緊張局勢尚未消退。下一章，你必須證明動員的力量也能守住人民的日常。'};if(s.relations>=75)return {title:'談判桌上的新席位',text:'你為群島爭取到更多合作空間。下一章，合作條件將進入議會，而選民會追問：誰能監督這些承諾？'};return {title:'尚未寫完的承諾',text:'這一天沒有簡單的勝利。有人開始信任你，有人仍在等待。下一章，你得回到選區，面對每一項選擇留下的問題。'};}
